export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_SIGNIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_LOGIN_FAIL";

export const GOOGLE_AUTH = "GOOGLE_AUTH";

export const LOG_OUT = "LOG_OUT";
